export const AUTH_LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const AUTH_LOGOUT = 'auth/LOGOUT';

export const UI_SET_NOTIFICATION = 'ui/SET_NOTIFICATION';
export const UI_REMOVE_NOTIFICATION = 'ui/REMOVE_NOTIFICATION';

export const ADVERTS_TAGS_LOADED = 'adverts/TAGS_LOADED';
export const ADVERTS_LOAD_REQUEST = 'adverts/LOAD_REQUEST';
export const ADVERTS_LOAD_SUCCESS = 'adverts/LOAD_SUCCESS';
export const ADVERTS_LOAD_FAILURE = 'adverts/LOAD_FAILURE';
export const ADVERTS_DELETE_REQUEST = 'adverts/DELETE_REQUEST';
export const ADVERTS_DELETE_SUCCESS = 'adverts/DELETE_SUCCESS';
export const ADVERTS_DELETE_FAILURE = 'adverts/DELETE_FAILURE';
export const ADVERTS_CREATE_REQUEST = 'adverts/CREATE_REQUEST';
export const ADVERTS_CREATE_SUCCESS = 'adverts/CREATE_SUCCESS';
export const ADVERTS_CREATE_FAILURE = 'adverts/CREATE_FAILURE';
